wandb_version: 1

config:
  desc: null
  value: config
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.5
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716976410.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.16.5
      8:
      - 1
      - 5
      13: linux-x86_64
